# The URL the site will be built for
base_url = "https://cheats.rs"
theme = "book"
compile_sass = true
build_search_index = false
check_external_links = true
highlight_code = false # We use prismjs for that